### PR TITLE
fix: fix generation of DAO objects with cycles

### LINKED ISSUE #1242: Generation of models with recursive associations fail
## Description

When generating models that are recursive, the current pullRelationships method will incorrectly provide an empty result if the value is already in the cache.

Snippet from: https://github.com/go-gorm/gen/blob/master/internal/generate/query.go#L253-L267
```
for i, relationship := range relationships {
		var childRelations []field.Relation
		varType := strings.TrimLeft(relationship.Field.FieldType.String(), "[]*")
		if !cache[varType] {
			cache[varType] = true
			childRelations = pullRelationShip(cache, append(append(append(append(
				make([]*schema.Relationship, 0, 4),
				relationship.FieldSchema.Relationships.BelongsTo...),
				relationship.FieldSchema.Relationships.HasOne...),
				relationship.FieldSchema.Relationships.HasMany...),
				relationship.FieldSchema.Relationships.Many2Many...),
			)
		}
		result[i] = *field.NewRelationWithType(field.RelationshipType(relationship.Type), relationship.Name, varType, childRelations...)
	}
```

See how if the value is in the cache, it will just be populared with an empty result.

For example, generating a model like this:

```
type User struct {
	Id       string    `gorm:"primaryKey"`
	Posts    []Post    `gorm:"foreignKey:AuthorId"`
	Comments []Comment `gorm:"foreignKey:AuthorId"`
}
type Post struct {
	Id       string `gorm:"primaryKey"`
	AuthorId string
	Author   User      `gorm:"foreignKey:Id"`
	Comments []Comment `gorm:"foreignKey:PostId"`
}
type Comment struct {
	Id       string `gorm:"primaryKey"`
	PostId   string
	Post     Post `gorm:"foreignKey:Id"`
	AuthorId string
	Author   User `gorm:"foreignKey:Id"`
}
```

pullRelationships will not correctly generate the User.Comments struct as it as already set the cached value to true when processing the User.Posts.Comments struct and will therefore return an empty definition of the relationship into the User object.

```
_user.Comments = userHasManyComments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Comments", "tests_test.Comment"),
	}
```

I have a fix https://github.com/Juice-Labs/gorm-gen/commit/85b4d1424c8eb3cb5a2ab02cff67d37e97341909#diff-76e4b5014eaf9f02f7aaa3e9430cb849f30c063494dd6afb0fc44672cbc763e9 with tests that alter the pullRelationship to build the entire cache before setting up the return values. This ensures that all types are correctly built.

I'm happy to open this change as a PR if you would accept this change or have any suggestions on how it should be changed.

Thanks

### PR DESCRIPTION
**Pull request by lloyd-juicelabs**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

When generating models that are recursive, the current pullRelationships method will incorrectly provide an empty result if the type is already in the cache.

This change alters the generator so it walks the tree twice, once to locate all the types and then a second time to actually generate all the code once the cache is correctly populated with all the types.

I have provided a test case ensure generation is working correctly.

fix #1242 

### User Case Description
Full bug description here: https://github.com/go-gorm/gen/issues/1242

### CODE REVIEW

File: internal/generate/query.go [hunk 1]
```diff
@@ -254,25 +254,32 @@ func isStructType(data reflect.Value) bool {
...
 			)
+			cache[varType] = childRelations
 		}
-		result[i] = *field.NewRelationWithType(field.RelationshipType(relationship.Type), relationship.Name, varType, childRelations...)
+	}
+
+	for i, relationship := range relationships {
+		varType := strings.TrimLeft(relationship.Field.FieldType.String(), "[]*")
+		cached := cache[varType]
+		result[i] = *field.NewRelationWithType(field.RelationshipType(relationship.Type), relationship.Name, varType, cached...)
```
Comment (tr1v3r) [inline internal/generate/query.go:282]: why rebuild a new relation type here?

Comment (lloyd-juicelabs) [reply internal/generate/query.go:282]: As far as I can tell this is needed as the cache just has the childRelations? I thought this is what the old code was doing, but the childRelations were just missing.

You have a better idea of how this should work though, so feel free to suggest something better or change my branch, my understanding is very surface level.

Comment (tr1v3r) [reply internal/generate/query.go:282]: Why does the implementation use a separate loop for assigning values to `result[i]` instead of performing the assignment within the initial loop, as seen in the original implementation? What are the technical considerations behind this design choice?

**Comment by tr1v3r** [comment]
Duplicate of #1270

File: internal/generate/query.go (hunk 1 above)
Comment (lloyd-juicelabs) [reply internal/generate/query.go:282]: This is the change that fixes the issue. We have to collect all the types before we build the interfaces. Previously it would encounter a type and use it immediately before it had fully walked that type. 

So if type A referenced type B and type B referenced type A, the the interface built on B would only be half implemented as the initial walk of A was half way through. Properties after B in A's interface were missing from A's interface on B.

This way we walk the entire tree, then once we have all the type information, we generate the interfaces and all the properties are correctly included.
